#!/usr/bin/env sh; C:/Program\ Files/Git/usr/bin/sh.exe
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-commit hook"
node node_modules/typescript/bin/tsc --noEmit
node node_modules/lint-staged/bin/lint-staged.js
